"""add_stat_allocation_columns

Revision ID: 26591ffe417c
Revises: f96206634cfa
Create Date: 2026-02-05 11:06:24.207982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26591ffe417c'
down_revision: Union[str, Sequence[str], None] = 'f96206634cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_buildings')
    op.alter_column('guilds', 'emblem',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('guilds', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    
    # Stat allocation columns (manually added for completeness)
    op.add_column('utente', sa.Column('stat_points', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_health', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_mana', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_damage', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_speed', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_resistance', sa.Integer(), server_default='0', nullable=True))
    op.add_column('utente', sa.Column('allocated_crit', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('guilds', 'emblem',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('utente', 'allocated_crit')
    op.drop_column('utente', 'allocated_resistance')
    op.drop_column('utente', 'allocated_speed')
    op.drop_column('utente', 'allocated_damage')
    op.drop_column('utente', 'allocated_mana')
    op.drop_column('utente', 'allocated_health')
    op.drop_column('utente', 'stat_points')
    
    op.create_table('guild_buildings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('building_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guild_buildings_pkey'))
    )
    # ### end Alembic commands ###
