"""Initial_migration

Revision ID: 840168b6a470
Revises: 
Create Date: 2026-01-30 15:39:53.871218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840168b6a470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giocoaroma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descrizione', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('from_chat', sa.String(), nullable=True),
    sa.Column('messageid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gruppo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('gruppo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'dungeon_participant', 'utente', ['user_id'], ['id_Telegram'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dungeon_participant', type_='foreignkey')
    op.drop_table('points')
    op.drop_table('gruppo')
    op.drop_table('giocoaroma')
    # ### end Alembic commands ###
