"""Add missing columns to utente

Revision ID: a414b899ae21
Revises: 1f6f17b8a3e0
Create Date: 2026-02-03 22:00:36.508196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a414b899ae21'
down_revision: Union[str, Sequence[str], None] = '1f6f17b8a3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crafting_queue')
    op.drop_table('guild_buildings')
    op.drop_table('user_equipment')
    op.drop_table('equipment')
    op.drop_table('resources')
    op.drop_table('user_resources')
    op.create_foreign_key(None, 'dungeon_participant', 'utente', ['user_id'], ['id_Telegram'])
    op.add_column('guilds', sa.Column('brewery_level', sa.Integer(), nullable=True))
    op.alter_column('market_listings', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('market_listings', 'buyer_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'market_listings', 'utente', ['seller_id'], ['id_Telegram'])
    op.create_foreign_key(None, 'market_listings', 'utente', ['buyer_id'], ['id_Telegram'])
    op.add_column('utente', sa.Column('last_beer_usage', sa.DateTime(), nullable=True))
    op.add_column('utente', sa.Column('last_brothel_usage', sa.DateTime(), nullable=True))
    op.add_column('utente', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utente', 'last_activity')
    op.drop_column('utente', 'last_brothel_usage')
    op.drop_column('utente', 'last_beer_usage')
    op.drop_constraint(None, 'market_listings', type_='foreignkey')
    op.drop_constraint(None, 'market_listings', type_='foreignkey')
    op.alter_column('market_listings', 'buyer_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('market_listings', 'seller_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('guilds', 'brewery_level')
    op.drop_constraint(None, 'dungeon_participant', type_='foreignkey')
    op.create_table('user_resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'drop'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_resources_pkey'))
    )
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rarity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drop_source', sa.VARCHAR(length=20), server_default=sa.text("'mob'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resources_pkey')),
    sa.UniqueConstraint('name', name=op.f('resources_name_key'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slot', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rarity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stats_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('min_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('effect_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crafting_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crafting_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('equipment_pkey'))
    )
    op.create_table('user_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipped', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('slot_equipped', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('user_equipment_equipment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['utente.id_Telegram'], name=op.f('user_equipment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_equipment_pkey'))
    )
    op.create_table('guild_buildings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('building_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guild_buildings_pkey'))
    )
    op.create_table('crafting_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completion_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'in_progress'::character varying"), autoincrement=False, nullable=True),
    sa.Column('actual_rarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('crafting_queue_pkey'))
    )
    # ### end Alembic commands ###
