"""add_user_skins_table

Revision ID: bee0b040d7a1
Revises: 3e9d8c7b6a5f
Create Date: 2026-02-05 11:57:38.154007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bee0b040d7a1'
down_revision: Union[str, Sequence[str], None] = '3e9d8c7b6a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('skin_id', sa.Integer(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('gif_path', sa.String(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skins_character_id'), 'user_skins', ['character_id'], unique=False)
    op.create_index(op.f('ix_user_skins_user_id'), 'user_skins', ['user_id'], unique=False)
    op.drop_table('guild_buildings')
    op.alter_column('guilds', 'emblem',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('guilds', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('guilds', 'emblem',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.create_table('guild_buildings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('building_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guild_buildings_pkey'))
    )
    op.drop_index(op.f('ix_user_skins_user_id'), table_name='user_skins')
    op.drop_index(op.f('ix_user_skins_character_id'), table_name='user_skins')
    op.drop_table('user_skins')
    # ### end Alembic commands ###
