"""Add_dungeon_hype_fields

Revision ID: d1d111bcb8eb
Revises: 840168b6a470
Create Date: 2026-01-30 15:56:54.808515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d111bcb8eb'
down_revision: Union[str, Sequence[str], None] = '840168b6a470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dungeon', sa.Column('hype_start_time', sa.DateTime(), nullable=True))
    op.add_column('dungeon', sa.Column('is_hype_active', sa.Boolean(), nullable=True))
    op.add_column('dungeon', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dungeon', 'scheduled_for')
    op.drop_column('dungeon', 'is_hype_active')
    op.drop_column('dungeon', 'hype_start_time')
    # ### end Alembic commands ###
